name: Create Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'

      # Add this step to give execute permissions to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

# Add this step to extract the version from settings.gradle
      - name: Extract version from settings.gradle
        id: extract-variable
        run: |
          getVersion=$(./gradlew -q getVersion)
          echo "version=$getVersion" >> $GITHUB_ENV

      - run: ./gradlew shadowJar && ./gradlew javadoc && mkdir staging && tar -cvf javadoc.zip build/docs/ && mv javadoc.zip staging/ && cp build/libs/*.jar staging/
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          automatic_release_tag: "${{ env.version }}"
          title: "Automated Build ${{ env.version }}"
          prerelease: false
          files: |
            staging/*.jar
            staging/*.zip